### ISSUE TITLE
Encourage using virtualenv

### ISSUE THREAD

**Issue by MrMrRobat** [geerlingguy/mac-dev-playbook#122]
Installing packages via pip to system python interpreter considered a bad practice and can lead to dependencies conflicts when multiple packages are installed/updated.

Instead, it's best to create [virtualenv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/#installing-virtualenv) for each individual tool. This way your system python will remain intact and tools dependencies will be isolated from each other. 

I can make a PR with changes required to encourage using venv to install dependencies. It would not be as straightforward as plain `pip install`, but may save a lot of time in the future.

What do you think?

**Comment by geerlingguy** [comment]
@MrMrRobat - So... that's a bit of a rabbit hole.

I'm guessing 90-95% of the people who use or will use this tool are not Python developers, and trying to introduce what I'd consider esoteric language-based best practices (like pyenv/venv stuff) is not something I want to have to do to get people jump-started with using Ansible.

It is better, that's definitely true. But it is not simpler, and I aim to keep the 'getting started' instructions as simple as possible.

For a seasoned Python developer, they'll already know about virtual environments and will know to just do that instead of using system Python for everything, but that's not my target audience for the README.

I'll leave the issue open though, in case someone knows a super dead-simple way to make it as easy as just setting the `$PATH` and using the system `pip3`.

**Comment by MrMrRobat** [comment]
Hmm, I see where you coming from.

Have you considered manually installing Homebrew first and then installing Ansible via Homebrew?

**Comment by geerlingguy** [comment]
The version of Ansible you get through Homebrew isn't quite as up-to-date, sometimes, and I'm not sure if they're sticking with the full Community distribution of Ansible, or just Ansible core...

**Comment by MrMrRobat** [comment]
The version in [Homebrew formula](https://formulae.brew.sh/formula/ansible) seems to be up to date with PyPi (4.0.0) and it uses ansible-core: https://github.com/Homebrew/homebrew-core/blob/45a3accc9ce9f6f2c7b051a2e82a798649d43360/Formula/ansible.rb#L57
