### ISSUE TITLE
Links to information about each homebrew package

### ISSUE THREAD

**Issue by wilsonmar** [geerlingguy/mac-dev-playbook#13]
Many may not know some of the homebrew packages.
So it would be helpful to have a link to each.
What are dependencies among them?

If I have time I'll complete that on my page:
https://wilsonmar.github.io/apple-mac-osx-setup/

**Comment by geerlingguy** [comment]
Since the project is meant more to help bootstrap a personalized environment, and for my purposes, I don't need that documentation, I'm going to close this issue—but a downstream project may take the time to better document all the packages being added... it would definitely be a bit more beginner-friendly.
