### ISSUE TITLE
Setting up multiple Macs on a hosted space

### ISSUE THREAD

**Issue by stephvgo** [geerlingguy/mac-dev-playbook#131]
Hello,
I'm pretty new to Ansible. From what I understand, this playbook can be used to set up a single Mac workspace.
How would I go about setting up this playbook to configure multiple Macs in a hosted space?
Thank you in advance. :)

**Comment by geerlingguy** [comment]
@stephvgo - It would require a little modification but would not be too hard; I wrote a book on Ansible, [Ansible for DevOps](https://www.ansiblefordevops.com), that targets more the Linux side of things but covers multi-server deployments more in depth.

But basically, you would change from just targeting one host in the inventory file to targeting a group, or using dynamic inventory; see https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

**Comment by toby-griffiths** [comment]
@stephvgo I've just done exactly this, (but for my single mac), since I wanted to be able to manage my entire home IT via a central server.  As Jeff suggested it was really just tweaking the inventory file to point to the remote host, once SSH was enabled, however I did need to pass the `ansible_become_password` variable through, since there's currently a bug with the standard `--ask-become-pass` sudo password being passed on to the mac collection roles… ah ignore that.  Jeff's just fixed it (https://github.com/geerlingguy/ansible-collection-mac/pull/13).

I can also, highly recommend the [Ansible for DevOps book](https://www.ansiblefordevops.com/) which I'm currently working through.
