### ISSUE TITLE
Sudo password asked twice

### ISSUE THREAD

**Issue by jiv-e** [geerlingguy/mac-dev-playbook#8]
Hi! Thanks for a great repo!

I launched the ansible-playbook command and left it running. I was hoping that after coming back the playbook would had finished. Instead it was stuck asking my sudo password again.

```
TASK: [geerlingguy.homebrew | Get list of apps installed with cask.] ********** 
Password:
```

Can this be avoided?

**Comment by geerlingguy** [comment]
@jiv-e - When you run the playbook, are you specifying `--ask-sudo-pass`, as in the readme? (`ansible-playbook main.yml -i inventory --ask-sudo-pass`). If you specify that option on the command line, Ansible will cache it so it doesn't need to prompt at all during the course of the playbook run. Otherwise, if the playbook takes more than 5 minutes to complete, it will ask for the password again in the middle of the run.
